config/routes.rb
ServePal::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get "" => "problems#index"

  resources :categories

  root to: 'problems#new'

  get "public/welcome"

  get 'public/login'

  resources :offers

  resources :problems do
    resources :categories
    resources :offers do
      resources :orders
    end
  end

  resources :profs do
    resources :problems do
      resources :offers
    end
  end

  get 'orders/:id/complete' => 'orders#complete', :as => :complete_order
  get 'orders/:id/incomplete' => 'orders#incomplete', :as => :incomplete_order

  resources :videos

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  attr_accessible :address, :description, :file, :name
  has_and_belongs_to_many :categories

  has_many :offers
  belongs_to :location


  mount_uploader :file, VideoFileUploader

  def title
    name
  end



  def prices
    offers.pluck(:price).compact
  end

  def price_range
    if prices.size == 0
      ""
    elsif prices.size == 1
      "#{prices.first}$"
    else
      "#{prices.min}$ - #{prices.max}$"
    end
  end

  def partial_user_name
    "Guy G."
  end

  def categories_html
    return "" unless categories
    categories.map(&:name).join ", "
  end

  def first_category
    categories[0] if categories.present?
  end

end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController

  before_filter do
    @prof = Prof.find_by_id(params[:prof_id]) if params[:prof_id]
  end
    ``
  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.order('id desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @problems }
    end
  end

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem = Problem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/1/edit
  def edit
    @problem = Problem.find(params[:id])
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(params[:problem])

    respond_to do |format|
      if @problem.save
        format.html { redirect_to edit_problem_path(@problem), notice: 'Problem was successfully updated.' }
        format.json { render json: @problem, status: :created, location: @problem }
      else
        format.html { render action: "new" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /problems/1
  # PUT /problems/1.json
  def update
    @problem = Problem.find(params[:id])

    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        #,"guy.gaash@gmail.com"                   guy@shopnfly.com;
        #NotifierMailer.send_profs(Prof.all[2], @problem, "masterweily@gmail.com").deliver
        #NotifierMailer.send_profs(Prof.all[1], @problem, "klarinas@gmail.com").deliver
        NotifierMailer.send_profs(Prof.first, @problem, "nitzanav@gmail.com",request).deliver
        #NotifierMailer.send_profs(Prof.first, @problem, "guy.gaash@gmail.com",request).deliver
        #NotifierMailer.send_profs(Prof.first, @problem, "masterweily@gmail.com",request).deliver

        format.html { redirect_to problem_offers_path(@problem), notice: 'Problem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy

    respond_to do |format|
      format.html { redirect_to problems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_video.html.erb
<video class="problem-video" controls>
  <!--<source src="<%= @problem.file %>" type="video/mp4" poster="<%#= @problem.file_url(:thumb)%>">-->
  <source src="<%= @problem.file %>" type="video/mp4">
  Your browser does not support the video tag.
</video>

app/views/problems/edit.html.erb
<link href="/Styles/create-request.min.css" rel="stylesheet" type="text/css" />

<%- model_class = Problem -%>

<%= form_for @problem, :html => { :class => 'edit_problem form-horizontal' } do |f| %>

  <div class="container">
    <div class="row">
      <div class="span4 offset4">

        <%= f.text_field :name, :class => 'input-block-level', :placeholder => "Title" %>
        <%= f.text_area :description, :rows => 3, :class => 'input-block-level', :placeholder => "Description" %>

        <%= f.file_field :file,
                         :class =>'input-block-level',
                         :accept => 'video/*;capture=camcorder' if false
        %>

        <video class="img" controls>
          <!--<source src="<%= @problem.file %>" type="video/mp4" poster="<%#= problem.file_url(:thumb)%>">-->
          <source src="<%= @problem.file %>" type="video/mp4">
          Your browser does not support the video tag.
        </video>


        <%= f.text_field :address, :class => 'input-block-level', :placeholder => "Location"  %>

        <%= link_to @problem.categories_html, problem_categories_path(@problem) if @problem.categories.present? %>
        <%= link_to "Add category", problem_categories_path(@problem) if @problem.categories.empty? %>
        <!--<select id="categories">-->
          <!--<option>Apple</option>-->
          <!--<option>Orange</option>-->
          <!--<option>Pineapple</option>-->
          <!--<option>Banana</option>-->
        <!--</select>-->

        <label class="checkbox" for="checkbox1">
          <span class="icons"><span class="first-icon fui-checkbox-unchecked"></span><span class="second-icon fui-checkbox-checked"></span></span>
          <input type="checkbox" value="" id="checkbox1" data-toggle="checkbox" />
          Post to Twitter
        </label>

        <label class="checkbox" for="checkbox2">
          <span class="icons"><span class="first-icon fui-checkbox-unchecked"></span><span class="second-icon fui-checkbox-checked"></span></span>
          <input type="checkbox" value="" id="checkbox2" data-toggle="checkbox" />
          Post to Facebook
        </label>

        <%= f.submit "Done", :class => 'btn btn-large btn-block btn-primary' %>

      </div>
    </div>
  </div>



<% end %>

app/views/problems/index.html.erb
<link href="/Styles/home.min.css" rel="stylesheet" type="text/css" />
<%= form_for Problem.new, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.file_field :file,
                   :class => 'file-field',
                   :accept => 'video/*;capture=camcorder'
  %>
    <%= f.submit %>

    <div class="container">
      <div class="row">
        <div class="span12 prof-types-list">
          <a href="#" class="btn btn-large btn-block btn-primary prof-types-list-link">Request Service</a>
        </div>
      </div>
      <hr />
  <% end %>

  <ul class="row" id="request-items">

    <% @problems.each do |problem| %>
      <%
         problem_link = prof_problem_path(@prof, problem) if @prof
         problem_link = problem_offers_path(problem) unless @prof
      %>
      <a href="<%= prof_problem_path(Prof.find(1), problem) %>">
        <li data-category-id-mod="1" class="request-item span6">
          <!--<video class="img" controls poster="<%#= problem.file_url(:thumb) %>">-->
          <video class="img" controls>
            <source src="<%= problem.file %>" type="video/mp4">
            Your browser does not support the video tag.
          </video>
          <section class="info">
            <label class="title"><%= problem.name %></label>
            <div class="details">
              <div class="detail">
                <label>Category</label><span><%= problem.first_category.try :name %></span>
              </div>
              <div class="detail">
                <label>Location</label><span><%= problem.address %></span>
              </div>
              <div class="detail">
                <label>Date</label><span><%= problem.created_at.strftime("%H:%M %m/%d/%Y") %></span>
              </div>
            </div>
          </section>
        </li>
      </a>

    <% end %>

  </ul>
  </div>





  <script src="/Scripts/app.js"></script>
  <!--<script src="/Scripts/home.js"></script>-->
  </body>
  </html>

app/views/problems/new.html.erb
<%- model_class = Problem -%>

<%= form_for @problem, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="control-group">

    <div class="controls">
      <%= f.file_field :file,
                       class: 'file-field',
                       accept: 'video/*;capture=camcorder',
                       style: 'display: none;'
      %>
    </div>

    <table class="prof-types-list">
      <% [["cleaning","doctor"],["handyman","moving"],["painting","plumbers"]].each do |row| %>
        <tr>
          <% row.each do |column| %>
            <td>
              <%= link_to '', class: 'prof-types-list' do %>
                <div class="prof-type">
                  <div class="icon" style="background-image: url(<%= "/assets/#{column}.png" %>)"></div>

                  <%#= image_tag("#{column}.png") %>

                  <%= content_tag :span, column.titleize %>
                </div>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>


<% end %>


<%= link_to "I am a proffional", profs_path, :style => "" %>

app/views/problems/show.html.erb
<link href="/Styles/view-request.min.css" rel="stylesheet" type="text/css" />

<%- model_class = Problem -%>
<div class="container">
  <div class="row">
    <div class="span12">

      <video id="video-container" controls>
        <source src="<%= @problem.file %>" type="video/mp4">
        Your browser does not support the video tag.
      </video>
      <hr />
      <h4 style="margin-bottom: 0px;"><%= @problem.name %></h4>
      <label style="color: #bbbbbb;"><%= @problem.first_category.try :name %>, <small><%= @problem.created_at.strftime("%H:%M %m/%d/%Y") %></small></label>
      <p id="request-description"><%= @problem.description %></p>
      <hr />

      Guy G.
      </br>
      </br>

      <div id="star"></div>
      <br/>
      <br/>


      <div style="overflow: auto;">
        <a style="float: left; margin: 0px; width: 75%" href="<%= new_prof_problem_offer_path(@prof, @problem) %>" class="btn btn-large btn-block btn-primary">Offer</a>
        <a style="float: left; margin: 0px; margin-left: 2%; width: 23%" href="<%= new_prof_problem_offer_path(@prof, @problem) %>" class="btn btn-large btn-block btn-info"><i class="icon-envelope"></i></a>
      </div>

      <section id="send-offer">
      </section>
      <%= @problem.address %>
      <div id="map" class="container">
        <div id="map_container"></div>
        <div id="other_content">
          <h2 id="loc">

          </h2>
        </div>
      </div>




    </div>

  </div>
</div>

<script src="/Scripts/external/jquery.min.js"></script>
<script src="/Scripts/external/bootstrap/js/bootstrap.min.js"></script>
<script src="/Scripts/app.js"></script>
<script src="/Scripts/external/flatui-checkbox.js"></script>
<script src="/Scripts/external/raty/jquery.raty.min.js"></script>
<script>$('#star').raty({ readOnly: true, score: 3 });



$.getScript('http://www.geoplugin.net/javascript.gp', function () {

  $('#loc').html("" + geoplugin_countryName() + ", " + geoplugin_region() + ", " + geoplugin_city());
  $('#map_container').css("background-image", "url(http://maps.google.com/maps/api/staticmap?center=" + geoplugin_city() + "," + geoplugin_region() + "&zoom=14&size=640x200&scale=1&markers=color:red%7C" + "32.067029" + "," + "34.795139" + "&maptype=terrain&sensor=true)");

});

</script>
<!--<script src="/Scripts/home.js"></script>-->