config/routes.rb
ServePal::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get "" => "problems#index"

  resources :categories

  root to: 'problems#new'

  get "public/welcome"

  get 'public/login'

  resources :offers

  resources :problems do
    resources :categories
    resources :offers do
      resources :orders
    end
  end

  resources :profs do
    resources :problems do
      resources :offers
    end
  end

  get 'orders/:id/complete' => 'orders#complete', :as => :complete_order
  get 'orders/:id/incomplete' => 'orders#incomplete', :as => :incomplete_order

  resources :videos

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :file

  mount_uploader :file, VideoFileUploader
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %><br />
    <%= f.file_field :file, accept: 'video/*;capture=camcorder' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <tr>
    <th>File</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.file %></td>
    <td><%= link_to 'Show', video %></td>
    <td><%= link_to 'Edit', edit_video_path(video) %></td>
    <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>File:</b>
  <%= @video.file %>
</p>


<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>