config/routes.rb
ServePal::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get "" => "problems#index"

  resources :categories

  root to: 'problems#new'

  get "public/welcome"

  get 'public/login'

  resources :offers

  resources :problems do
    resources :categories
    resources :offers do
      resources :orders
    end
  end

  resources :profs do
    resources :problems do
      resources :offers
    end
  end

  get 'orders/:id/complete' => 'orders#complete', :as => :complete_order
  get 'orders/:id/incomplete' => 'orders#incomplete', :as => :incomplete_order

  resources :videos

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  attr_accessible :arrival, :free_text, :price, :problem_id, :prof_id

  belongs_to :prof
  belongs_to :problem
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  before_filter do
    @prof = Prof.find_by_id(params[:prof_id]) if params[:prof_id]
    @problem = Problem.find_by_id(params[:problem_id]) if params[:problem_id]
  end

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer
    @offers = @offers.where(:prof_id => @prof.id) if @prof
    @offers = @offers.where(:problem_id => @problem.id) if @problem
    @offers = @offers.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offers }
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @offer = Offer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/new
  # GET /offers/new.json
  def new
    @offer = Offer.new(:problem_id => @problem.id, :prof_id => @prof.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(params[:offer])

    respond_to do |format|
      if @offer.save
        #UserNotifier.send_users(@prof, @problem, @offer, "masterweily@gmail.com",request).deliver
        #UserNotifier.send_users(@prof, @problem, @offer, "nitzanav@gmail.com",request).deliver
        #UserNotifier.send_users(@prof, @problem, @offer, "masterweily@gmail.com",request).deliver
        #UserNotifier.send_users(@prof, @problem, @offer, "leoshpitz@shopnfly.com").deliver
        #UserNotifier.send_users(@prof, @problem, @offer, "guy@shopnfly.com").deliver
        UserNotifier.send_users(@prof, @problem, @offer, "guy.gaash@gmail.com",request).deliver

        format.html { redirect_to prof_problems_path(@prof), notice: 'Offer was successfully created.' }
        format.json { render json: @offer, status: :created, location: @offer }
      else
        format.html { render action: "new" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.json
  def update
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for [@prof, @problem, @offer], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">

  <%= f.hidden_field :problem_id, :class => 'number_field' %>
  <%= f.hidden_field :prof_id, :class => 'number_field' %>

  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :price, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :arrival, "Time of Arrival", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :arrival, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :free_text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :free_text, :class => 'text_field', :rows => 4 %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                offers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/offers/index.html.erb
<%- model_class = Offer -%>



  <link href="/Styles/inbox.min.css" rel="stylesheet" type="text/css" />

<% if @offers.empty? %>
  <h4>No new notifications.</h4>
<% end %>

<% @offers.each do |offer| %>

<section class="request">
  <header><%= offer.problem.name %></header>
  <ul class="container-fluid notifications">


    <%= link_to problem_offer_path(offer.problem,offer) do %>
      <li class="mobile-row-fluid notification new-offer">
        <div class="span3">
          <img class="user-img" src="/Images/demoClient.jpg" />
        </div>
        <div class="span6">
          <h4 style="margin: 0px;"><%= offer.prof.name %></h4>
          <div class="rating" style="display: inline-table; margin-top: 3px;"></div>
        </div>
        <div class="span3">
          <span class="offer-price"><%= offer.price %>$</span>
          <span class="new-msgs"></span>
        </div>
      </li>
    <% end %>


    <li class="mobile-row-fluid notification new-chat">
      <div class="span3">
        <img class="user-img" src="/Images/demoClient.jpg" />
      </div>
      <div class="span7">
        <h4 style="margin: 0px;"><%= offer.prof.name %></h4>
        <div class="rating" style="display: inline-table; margin-top: 3px;"></div>

      </div>
      <div class="span2">
        <span class="offer-price"></span>
        <span class="new-msgs">3</span>
      </div>
    </li>


  </ul>


</section>


<% end %>

app/views/offers/new.html.erb
<%- model_class = Offer -%>
<div class="page-header">
  <h1>
    Offer for - <%= @problem.name %>
  </h1>
</div>
<%= render :partial => 'form' %>

app/views/offers/show.html.erb
<%- model_class = Offer -%>
<link href="/Styles/offer.min.css" rel="stylesheet" type="text/css" />

<div class="container">
  <div class="row">
    <div class="span12">

      <h4 style="margin-top: -10px;">@offer.problem.name</h4>

      <section id="offer-info">

        <div>
          <label>Supplier Name:</label><span><%= @offer.prof.name %>
                        </span>
        </div>
        <div>
          <label>Rating:</label><span><div class="rating"></div>
                        </span>
        </div>
        <div>
          <label>Time Of Arrival:</label><span>09:10 11/12/2013</span>
        </div>

        <span class="price"><%= @offer.price %>$</span>


      </section>

      <%= link_to problem_offer_orders_path(@offer.problem,@offer),:method => :post, :class => 'btn btn-large btn-block btn-infos' do %>
        <i class="icon-hand-right" style="margin-right:5px;"></i>
        Order with Paypal
      <% end %>



        <section id="chat">
        <header>Chat</header>

        <div style="overflow: auto; margin-bottom: 10px;">
          <input id="input-new-chat" type="text" style="float: left; margin: 0px; width: 70%" />
          <a id="btn-new-chat" style="float: left; margin: 0px; margin-left: 2%; width: 23%; height: 41px;" class="btn btn-large btn-block btn-inverse"><i class="icon-envelope"></i></a>

        </div>

        <ul>
          <li class="me">hi, whats your name?</li>
          <li class="me">alo ??</li>
          <li class="him">yes?</li>
          <li class="me">whats your name?</li>
          <li class="him">Heroku, and you?</li>
          <li class="me">I'm Hasan</li>
          <li class="him">OK</li>
          <li class="him">How can i help you?</li>
          <li class="me">this is a very long chat ok !! so if u don't like it go to hill please okk !??!</li>
        </ul>


      </section>

      <hr />

      <section id="supplier-info">
        <img class="img" src="/Images/demo-client-large.jpg" />
        <h2 class="name">Mr. Get Bales</h2>
        <p class="description">He is consistently ranked in the Forbes list of the world's wealthiest people[5] and was the wealthiest overall from 1995 to 2009—excluding 2008, when he was ranked third;[6] in 2011 he was the wealthiest American and the world's second wealthiest person.[7][8] According to the Bloomberg Billionaires List, Gates is the world's richest person in 2013, a position that he last held on the list in 2007</p>
      </section>

    </div>
  </div>
</div>

<script src="Scripts/external/jquery.min.js"></script>
<script src="Scripts/external/bootstrap/js/bootstrap.min.js"></script>
<script src="/Scripts/app.js"></script>
<script src="Scripts/external/flatui-checkbox.js"></script>
<script src="Scripts/external/raty/jquery.raty.min.js"></script>
<script>$('.rating').raty({ readOnly: true, score: 5 });
</script>
<!--<script src="/Scripts/home.js"></script>-->
</body>
</html>